-- Final literal candidate for prisma/migrations/20260823040000_installation_private_media/migration.sql.
-- Prepared for the orchestrator; intentionally not written into the repository.
CREATE TABLE "InstallationFile" (
  "id" TEXT NOT NULL PRIMARY KEY, "orderId" TEXT NOT NULL, "roomId" TEXT, "scopeId" TEXT, "formSubmissionId" TEXT, "clientLinkId" TEXT, "mobileHandoffId" TEXT, "purpose" TEXT NOT NULL, "questionKey" TEXT, "originalFilename" TEXT NOT NULL, "contentType" TEXT NOT NULL, "byteSize" INTEGER, "sha256" TEXT, "status" TEXT NOT NULL DEFAULT 'PENDING', "failureReason" TEXT, "source" TEXT NOT NULL DEFAULT 'WEB', "createdById" TEXT, "softDeletedAt" DATETIME, "softDeletedById" TEXT, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL,
  CONSTRAINT "InstallationFile_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "InstallationOrder" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT "InstallationFile_roomId_fkey" FOREIGN KEY ("roomId") REFERENCES "InstallationRoom" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT "InstallationFile_scopeId_fkey" FOREIGN KEY ("scopeId") REFERENCES "InstallationScope" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT "InstallationFile_formSubmissionId_fkey" FOREIGN KEY ("formSubmissionId") REFERENCES "InstallationFormSubmission" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT "InstallationFile_clientLinkId_fkey" FOREIGN KEY ("clientLinkId") REFERENCES "InstallationClientLink" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT "InstallationFile_mobileHandoffId_fkey" FOREIGN KEY ("mobileHandoffId") REFERENCES "MobileUploadHandoff" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE INDEX "InstallationFile_orderId_purpose_questionKey_status_softDeletedAt_idx" ON "InstallationFile"("orderId","purpose","questionKey","status","softDeletedAt");
CREATE INDEX "InstallationFile_roomId_createdAt_idx" ON "InstallationFile"("roomId","createdAt");
CREATE INDEX "InstallationFile_scopeId_createdAt_idx" ON "InstallationFile"("scopeId","createdAt");
CREATE INDEX "InstallationFile_formSubmissionId_questionKey_idx" ON "InstallationFile"("formSubmissionId","questionKey");
CREATE INDEX "InstallationFile_clientLinkId_questionKey_idx" ON "InstallationFile"("clientLinkId","questionKey");
CREATE INDEX "InstallationFile_mobileHandoffId_idx" ON "InstallationFile"("mobileHandoffId");

CREATE TABLE "InstallationMismatchEvidence" (
  "id" TEXT NOT NULL PRIMARY KEY, "orderId" TEXT NOT NULL, "mismatchId" TEXT NOT NULL, "fileId" TEXT NOT NULL, "attachedById" TEXT NOT NULL, "attachedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "InstallationMismatchEvidence_mismatchId_key" UNIQUE ("mismatchId"), CONSTRAINT "InstallationMismatchEvidence_fileId_key" UNIQUE ("fileId"),
  CONSTRAINT "InstallationMismatchEvidence_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "InstallationOrder" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT "InstallationMismatchEvidence_mismatchId_fkey" FOREIGN KEY ("mismatchId") REFERENCES "InstallationMismatch" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT "InstallationMismatchEvidence_fileId_fkey" FOREIGN KEY ("fileId") REFERENCES "InstallationFile" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE INDEX "InstallationMismatchEvidence_orderId_fileId_idx" ON "InstallationMismatchEvidence"("orderId","fileId");

CREATE TABLE "MobileUploadHandoff" (
  "id" TEXT NOT NULL PRIMARY KEY, "orderId" TEXT NOT NULL, "clientLinkId" TEXT NOT NULL, "formSubmissionId" TEXT NOT NULL, "questionKey" TEXT NOT NULL, "codeHash" TEXT NOT NULL, "sessionSecretHash" TEXT, "allowedMimeJson" TEXT NOT NULL, "maxFiles" INTEGER NOT NULL DEFAULT 5, "usedFiles" INTEGER NOT NULL DEFAULT 0, "maxByteSize" INTEGER NOT NULL DEFAULT 10485760, "expiresAt" DATETIME NOT NULL, "redeemedAt" DATETIME, "revokedAt" DATETIME, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL,
  CONSTRAINT "MobileUploadHandoff_codeHash_key" UNIQUE ("codeHash"), CONSTRAINT "MobileUploadHandoff_sessionSecretHash_key" UNIQUE ("sessionSecretHash"),
  CONSTRAINT "MobileUploadHandoff_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "InstallationOrder" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT "MobileUploadHandoff_clientLinkId_fkey" FOREIGN KEY ("clientLinkId") REFERENCES "InstallationClientLink" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT "MobileUploadHandoff_formSubmissionId_fkey" FOREIGN KEY ("formSubmissionId") REFERENCES "InstallationFormSubmission" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE INDEX "MobileUploadHandoff_clientLinkId_expiresAt_revokedAt_idx" ON "MobileUploadHandoff"("clientLinkId","expiresAt","revokedAt");
CREATE INDEX "MobileUploadHandoff_orderId_questionKey_idx" ON "MobileUploadHandoff"("orderId","questionKey");

CREATE TABLE "InstallationFileAuditEvent" (
  "id" TEXT NOT NULL PRIMARY KEY, "fileId" TEXT NOT NULL, "orderId" TEXT NOT NULL, "actorId" TEXT NOT NULL, "action" TEXT NOT NULL, "metadataJson" TEXT, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "InstallationFileAuditEvent_fileId_fkey" FOREIGN KEY ("fileId") REFERENCES "InstallationFile" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT "InstallationFileAuditEvent_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "InstallationOrder" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE INDEX "InstallationFileAuditEvent_fileId_createdAt_idx" ON "InstallationFileAuditEvent"("fileId","createdAt");
CREATE INDEX "InstallationFileAuditEvent_orderId_createdAt_idx" ON "InstallationFileAuditEvent"("orderId","createdAt");

CREATE TRIGGER "InstallationFile_shape_insert_guard" BEFORE INSERT ON "InstallationFile"
WHEN NEW."purpose" NOT IN ('CLIENT_QUESTION','MISMATCH_EVIDENCE','INTERNAL_PROJECT') OR NEW."status" IS NOT 'PENDING' OR NEW."source" NOT IN ('WEB','MOBILE_QR','INTERNAL') OR NEW."contentType" NOT IN ('image/jpeg','image/png','image/webp','application/pdf') OR NEW."byteSize" IS NOT NULL OR NEW."sha256" IS NOT NULL OR NEW."failureReason" IS NOT NULL
BEGIN SELECT RAISE(ABORT,'installation file must start PENDING'); END;
CREATE TRIGGER "InstallationFile_shape_update_guard" BEFORE UPDATE OF "contentType","byteSize","sha256","status","failureReason","source" ON "InstallationFile"
WHEN NEW."status" NOT IN ('PENDING','READY','FAILED') OR NEW."source" NOT IN ('WEB','MOBILE_QR','INTERNAL') OR NEW."contentType" NOT IN ('image/jpeg','image/png','image/webp','application/pdf') OR (NEW."status"='READY' AND (NEW."byteSize" IS NULL OR NEW."byteSize"<1 OR NEW."sha256" IS NULL OR length(NEW."sha256")<>64 OR NEW."sha256" GLOB '*[^0-9a-f]*' OR NEW."failureReason" IS NOT NULL)) OR (NEW."status"='PENDING' AND (NEW."byteSize" IS NOT NULL OR NEW."sha256" IS NOT NULL OR NEW."failureReason" IS NOT NULL)) OR (NEW."status"='FAILED' AND (NEW."byteSize" IS NOT NULL OR NEW."sha256" IS NOT NULL OR length(trim(COALESCE(NEW."failureReason",'')))=0))
BEGIN SELECT RAISE(ABORT,'installation file metadata is invalid'); END;
CREATE TRIGGER "InstallationFile_status_transition_guard" BEFORE UPDATE OF "status" ON "InstallationFile"
WHEN NOT (OLD."status"='PENDING' AND NEW."status" IN ('READY','FAILED'))
BEGIN SELECT RAISE(ABORT,'installation file status cannot be downgraded or replaced'); END;
CREATE TRIGGER "InstallationFile_target_update_guard" BEFORE UPDATE OF "orderId","roomId","scopeId","formSubmissionId","clientLinkId","mobileHandoffId","purpose","questionKey","originalFilename","contentType","source","createdById" ON "InstallationFile"
WHEN NEW."orderId" IS NOT OLD."orderId" OR NEW."roomId" IS NOT OLD."roomId" OR NEW."scopeId" IS NOT OLD."scopeId" OR NEW."formSubmissionId" IS NOT OLD."formSubmissionId" OR NEW."clientLinkId" IS NOT OLD."clientLinkId" OR NEW."mobileHandoffId" IS NOT OLD."mobileHandoffId" OR NEW."purpose" IS NOT OLD."purpose" OR NEW."questionKey" IS NOT OLD."questionKey" OR NEW."originalFilename" IS NOT OLD."originalFilename" OR NEW."contentType" IS NOT OLD."contentType" OR NEW."source" IS NOT OLD."source" OR NEW."createdById" IS NOT OLD."createdById"
BEGIN SELECT RAISE(ABORT,'installation file target is immutable'); END;
CREATE TRIGGER "InstallationFile_terminal_metadata_update_guard" BEFORE UPDATE OF "originalFilename","contentType","byteSize","sha256","failureReason","source","createdById" ON "InstallationFile"
WHEN OLD."status" IN ('READY','FAILED') AND (NEW."originalFilename" IS NOT OLD."originalFilename" OR NEW."contentType" IS NOT OLD."contentType" OR NEW."byteSize" IS NOT OLD."byteSize" OR NEW."sha256" IS NOT OLD."sha256" OR NEW."failureReason" IS NOT OLD."failureReason" OR NEW."source" IS NOT OLD."source" OR NEW."createdById" IS NOT OLD."createdById")
BEGIN SELECT RAISE(ABORT,'terminal installation file metadata is immutable'); END;
CREATE TRIGGER "InstallationFile_soft_delete_guard" BEFORE UPDATE OF "softDeletedAt","softDeletedById" ON "InstallationFile"
WHEN (OLD."softDeletedAt" IS NOT NULL AND (NEW."softDeletedAt" IS NOT OLD."softDeletedAt" OR NEW."softDeletedById" IS NOT OLD."softDeletedById")) OR (OLD."softDeletedAt" IS NULL AND NEW."softDeletedAt" IS NOT NULL AND length(trim(COALESCE(NEW."softDeletedById",'')))=0) OR (OLD."softDeletedAt" IS NULL AND NEW."softDeletedAt" IS NULL AND NEW."softDeletedById" IS NOT NULL)
BEGIN SELECT RAISE(ABORT,'installation file soft-delete is one-way and attributable'); END;
CREATE TRIGGER "InstallationFile_attached_evidence_update_guard" BEFORE UPDATE OF "status","softDeletedAt","softDeletedById" ON "InstallationFile"
WHEN EXISTS (SELECT 1 FROM "InstallationMismatchEvidence" e WHERE e."fileId"=OLD."id") AND (NEW."status" IS NOT OLD."status" OR NEW."softDeletedAt" IS NOT OLD."softDeletedAt" OR NEW."softDeletedById" IS NOT OLD."softDeletedById")
BEGIN SELECT RAISE(ABORT,'attached mismatch evidence file cannot be downgraded or deleted'); END;
CREATE TRIGGER "InstallationFile_target_insert_guard" BEFORE INSERT ON "InstallationFile"
WHEN (NEW."roomId" IS NOT NULL AND NOT EXISTS (SELECT 1 FROM "InstallationRoom" r WHERE r."id"=NEW."roomId" AND r."orderId"=NEW."orderId")) OR (NEW."scopeId" IS NOT NULL AND NOT EXISTS (SELECT 1 FROM "InstallationScope" s JOIN "InstallationRoom" r ON r."id"=s."roomId" WHERE s."id"=NEW."scopeId" AND r."orderId"=NEW."orderId")) OR (NEW."roomId" IS NOT NULL AND NEW."scopeId" IS NOT NULL AND NOT EXISTS (SELECT 1 FROM "InstallationScope" s WHERE s."id"=NEW."scopeId" AND s."roomId"=NEW."roomId")) OR (NEW."purpose"='CLIENT_QUESTION' AND (NEW."formSubmissionId" IS NULL OR NEW."clientLinkId" IS NULL OR length(trim(COALESCE(NEW."questionKey",'')))=0 OR NEW."roomId" IS NOT NULL OR NEW."scopeId" IS NOT NULL OR NOT EXISTS (SELECT 1 FROM "InstallationFormSubmission" s WHERE s."id"=NEW."formSubmissionId" AND s."orderId"=NEW."orderId" AND s."status"='DRAFT') OR NOT EXISTS (SELECT 1 FROM "InstallationClientLink" l WHERE l."id"=NEW."clientLinkId" AND l."orderId"=NEW."orderId" AND l."revokedAt" IS NULL AND ((typeof(l."expiresAt") IN ('integer','real') AND l."expiresAt">CAST(strftime('%s','now') AS INTEGER)*1000) OR (typeof(l."expiresAt")='text' AND julianday(l."expiresAt")>julianday('now')))) OR (NEW."mobileHandoffId" IS NULL AND NEW."source" IS NOT 'WEB') OR (NEW."mobileHandoffId" IS NOT NULL AND (NEW."source" IS NOT 'MOBILE_QR' OR NOT EXISTS (SELECT 1 FROM "MobileUploadHandoff" h WHERE h."id"=NEW."mobileHandoffId" AND h."orderId"=NEW."orderId" AND h."clientLinkId"=NEW."clientLinkId" AND h."formSubmissionId"=NEW."formSubmissionId" AND h."questionKey"=NEW."questionKey" AND h."sessionSecretHash" IS NOT NULL AND h."redeemedAt" IS NOT NULL AND h."revokedAt" IS NULL AND ((typeof(h."expiresAt") IN ('integer','real') AND h."expiresAt">CAST(strftime('%s','now') AS INTEGER)*1000) OR (typeof(h."expiresAt")='text' AND julianday(h."expiresAt")>julianday('now')))))))) OR (NEW."purpose"='MISMATCH_EVIDENCE' AND (NEW."formSubmissionId" IS NOT NULL OR NEW."clientLinkId" IS NOT NULL OR NEW."mobileHandoffId" IS NOT NULL OR NEW."questionKey" IS NOT NULL OR NEW."roomId" IS NOT NULL OR NEW."scopeId" IS NOT NULL OR NEW."source" IS NOT 'INTERNAL')) OR (NEW."purpose"='INTERNAL_PROJECT' AND (NEW."formSubmissionId" IS NOT NULL OR NEW."clientLinkId" IS NOT NULL OR NEW."mobileHandoffId" IS NOT NULL OR NEW."questionKey" IS NOT NULL OR NEW."source" IS NOT 'INTERNAL'))
BEGIN SELECT RAISE(ABORT,'installation file target does not belong to this order'); END;

CREATE TRIGGER "MobileUploadHandoff_insert_guard" BEFORE INSERT ON "MobileUploadHandoff"
WHEN length(trim(NEW."questionKey"))=0 OR length(NEW."codeHash")<>64 OR NEW."codeHash" GLOB '*[^0-9a-f]*' OR NEW."sessionSecretHash" IS NOT NULL OR NEW."redeemedAt" IS NOT NULL OR NEW."maxFiles"<1 OR NEW."maxFiles">5 OR NEW."usedFiles"<0 OR NEW."usedFiles">NEW."maxFiles" OR NEW."maxByteSize"<1 OR NEW."maxByteSize">10485760 OR NOT ((typeof(NEW."expiresAt") IN ('integer','real') AND NEW."expiresAt">CAST(strftime('%s','now') AS INTEGER)*1000) OR (typeof(NEW."expiresAt")='text' AND julianday(NEW."expiresAt")>julianday('now'))) OR NOT EXISTS (SELECT 1 FROM "InstallationClientLink" l WHERE l."id"=NEW."clientLinkId" AND l."orderId"=NEW."orderId" AND l."revokedAt" IS NULL AND ((typeof(l."expiresAt") IN ('integer','real') AND l."expiresAt">CAST(strftime('%s','now') AS INTEGER)*1000) OR (typeof(l."expiresAt")='text' AND julianday(l."expiresAt")>julianday('now')))) OR NOT EXISTS (SELECT 1 FROM "InstallationFormSubmission" s WHERE s."id"=NEW."formSubmissionId" AND s."orderId"=NEW."orderId" AND s."status"='DRAFT')
BEGIN SELECT RAISE(ABORT,'mobile handoff target, expiry or limits are invalid'); END;
CREATE TRIGGER "MobileUploadHandoff_target_update_guard" BEFORE UPDATE OF "orderId","clientLinkId","formSubmissionId","questionKey","codeHash","allowedMimeJson","maxFiles","maxByteSize","expiresAt" ON "MobileUploadHandoff"
WHEN NEW."orderId" IS NOT OLD."orderId" OR NEW."clientLinkId" IS NOT OLD."clientLinkId" OR NEW."formSubmissionId" IS NOT OLD."formSubmissionId" OR NEW."questionKey" IS NOT OLD."questionKey" OR NEW."codeHash" IS NOT OLD."codeHash" OR NEW."allowedMimeJson" IS NOT OLD."allowedMimeJson" OR NEW."maxFiles" IS NOT OLD."maxFiles" OR NEW."maxByteSize" IS NOT OLD."maxByteSize" OR NEW."expiresAt" IS NOT OLD."expiresAt"
BEGIN SELECT RAISE(ABORT,'mobile handoff target is immutable'); END;
CREATE TRIGGER "MobileUploadHandoff_state_update_guard" BEFORE UPDATE OF "sessionSecretHash","usedFiles","redeemedAt","revokedAt" ON "MobileUploadHandoff"
WHEN (NEW."sessionSecretHash" IS NOT NULL AND (length(NEW."sessionSecretHash")<>64 OR NEW."sessionSecretHash" GLOB '*[^0-9a-f]*')) OR ((OLD."sessionSecretHash" IS NULL AND NEW."sessionSecretHash" IS NOT NULL) <> (OLD."redeemedAt" IS NULL AND NEW."redeemedAt" IS NOT NULL)) OR (OLD."sessionSecretHash" IS NOT NULL AND NEW."sessionSecretHash" IS NOT OLD."sessionSecretHash") OR (OLD."redeemedAt" IS NOT NULL AND NEW."redeemedAt" IS NOT OLD."redeemedAt") OR (OLD."revokedAt" IS NOT NULL AND NEW."revokedAt" IS NOT OLD."revokedAt") OR NEW."usedFiles"<OLD."usedFiles" OR NEW."usedFiles">OLD."usedFiles"+1 OR NEW."usedFiles">NEW."maxFiles"
BEGIN SELECT RAISE(ABORT,'mobile handoff state is invalid'); END;

CREATE TRIGGER "InstallationFileAuditEvent_insert_guard" BEFORE INSERT ON "InstallationFileAuditEvent"
WHEN NEW."action" NOT IN ('INSTALLATION_PRIVATE_FILE_PENDING','INSTALLATION_PRIVATE_FILE_READY','INSTALLATION_PRIVATE_FILE_FAILED','INSTALLATION_PRIVATE_FILE_SOFT_DELETED','INSTALLATION_PRIVATE_FILE_DELETE_REMOTE_FAILED','INSTALLATION_MISMATCH_PRIVATE_EVIDENCE_ATTACHED') OR NOT EXISTS (SELECT 1 FROM "InstallationFile" f WHERE f."id"=NEW."fileId" AND f."orderId"=NEW."orderId")
BEGIN SELECT RAISE(ABORT,'installation file audit event is invalid'); END;
CREATE TRIGGER "InstallationFileAuditEvent_update_guard" BEFORE UPDATE ON "InstallationFileAuditEvent" BEGIN SELECT RAISE(ABORT,'installation file audit event is immutable'); END;
CREATE TRIGGER "InstallationFileAuditEvent_delete_guard" BEFORE DELETE ON "InstallationFileAuditEvent" BEGIN SELECT RAISE(ABORT,'installation file audit event is immutable'); END;

DROP TRIGGER "InstallationMismatch_task5_verification_insert_guard";
DROP TRIGGER "InstallationMismatch_task5_verification_update_guard";
DROP TRIGGER "InstallationBillingTask_mismatch_approval_guard";
DROP TRIGGER "InstallationBillingTask_mismatch_approval_update_guard";
CREATE TRIGGER "InstallationMismatch_private_evidence_insert_guard" BEFORE INSERT ON "InstallationMismatch"
WHEN NEW."evidenceStatus"='VERIFIED_PRIVATE_FILE' OR NEW."evidenceFileId" IS NOT NULL OR NEW."evidenceVerifiedAt" IS NOT NULL
BEGIN SELECT RAISE(ABORT,'mismatch private evidence must be attached after creation'); END;
CREATE TRIGGER "InstallationMismatch_private_evidence_update_guard" BEFORE UPDATE OF "evidenceStatus","evidenceFileId","evidenceVerifiedAt" ON "InstallationMismatch"
WHEN (NEW."evidenceStatus" IS NOT OLD."evidenceStatus" OR NEW."evidenceFileId" IS NOT OLD."evidenceFileId" OR NEW."evidenceVerifiedAt" IS NOT OLD."evidenceVerifiedAt") AND NOT ((OLD."evidenceStatus"='VERIFIED_PRIVATE_FILE' AND NEW."evidenceStatus"='PENDING_PRIVATE_FILE' AND NEW."evidenceFileId" IS NULL AND NEW."evidenceVerifiedAt" IS NULL AND NOT EXISTS (SELECT 1 FROM "InstallationBillingTask" b WHERE b."mismatchId"=OLD."id" AND b."kind"='MISMATCH_VISIT_FEE')) OR (NEW."evidenceStatus"='VERIFIED_PRIVATE_FILE' AND NEW."evidenceFileId" IS NOT NULL AND NEW."evidenceVerifiedAt" IS NOT NULL AND ((typeof(NEW."evidenceVerifiedAt") IN ('integer','real') AND NEW."evidenceVerifiedAt"<=CAST(strftime('%s','now') AS INTEGER)*1000) OR (typeof(NEW."evidenceVerifiedAt")='text' AND julianday(NEW."evidenceVerifiedAt")<=julianday('now'))) AND EXISTS (SELECT 1 FROM "InstallationMismatchEvidence" e JOIN "InstallationFile" f ON f."id"=e."fileId" WHERE e."mismatchId"=NEW."id" AND e."orderId"=NEW."orderId" AND e."fileId"=NEW."evidenceFileId" AND f."orderId"=NEW."orderId" AND f."purpose"='MISMATCH_EVIDENCE' AND f."status"='READY' AND f."softDeletedAt" IS NULL AND f."byteSize">0 AND length(f."sha256")=64 AND f."sha256" NOT GLOB '*[^0-9a-f]*' AND EXISTS (SELECT 1 FROM "InstallationFileAuditEvent" a WHERE a."fileId"=f."id" AND a."orderId"=NEW."orderId" AND a."action"='INSTALLATION_PRIVATE_FILE_READY'))))
BEGIN SELECT RAISE(ABORT,'verified mismatch requires ready same-order private evidence'); END;
CREATE TRIGGER "InstallationMismatchEvidence_insert_guard" BEFORE INSERT ON "InstallationMismatchEvidence"
WHEN NOT EXISTS (SELECT 1 FROM "InstallationMismatch" m JOIN "InstallationFile" f ON f."id"=NEW."fileId" WHERE m."id"=NEW."mismatchId" AND m."orderId"=NEW."orderId" AND m."evidenceStatus"='PENDING_PRIVATE_FILE' AND f."orderId"=NEW."orderId" AND f."purpose"='MISMATCH_EVIDENCE' AND f."status"='READY' AND f."softDeletedAt" IS NULL AND f."formSubmissionId" IS NULL AND f."clientLinkId" IS NULL AND f."mobileHandoffId" IS NULL AND f."roomId" IS NULL AND f."scopeId" IS NULL AND f."questionKey" IS NULL AND f."byteSize">0 AND length(f."sha256")=64 AND f."sha256" NOT GLOB '*[^0-9a-f]*' AND EXISTS (SELECT 1 FROM "InstallationFileAuditEvent" a WHERE a."fileId"=f."id" AND a."orderId"=NEW."orderId" AND a."action"='INSTALLATION_PRIVATE_FILE_READY'))
BEGIN SELECT RAISE(ABORT,'mismatch evidence must be a ready same-order private file'); END;
CREATE TRIGGER "InstallationMismatchEvidence_update_guard" BEFORE UPDATE ON "InstallationMismatchEvidence" BEGIN SELECT RAISE(ABORT,'mismatch evidence bridge is immutable'); END;
CREATE TRIGGER "InstallationMismatchEvidence_billed_delete_guard" BEFORE DELETE ON "InstallationMismatchEvidence" WHEN EXISTS (SELECT 1 FROM "InstallationBillingTask" b WHERE b."mismatchId"=OLD."mismatchId" AND b."kind"='MISMATCH_VISIT_FEE') OR NOT EXISTS (SELECT 1 FROM "InstallationMismatch" m WHERE m."id"=OLD."mismatchId" AND m."orderId"=OLD."orderId" AND m."evidenceStatus"='PENDING_PRIVATE_FILE' AND m."evidenceFileId" IS NULL AND m."evidenceVerifiedAt" IS NULL) BEGIN SELECT RAISE(ABORT,'mismatch evidence may be removed only after an unbilled atomic downgrade'); END;
CREATE TRIGGER "InstallationFile_billed_evidence_update_guard" BEFORE UPDATE OF "originalFilename","contentType","byteSize","sha256","status","failureReason","source","softDeletedAt","softDeletedById" ON "InstallationFile" WHEN EXISTS (SELECT 1 FROM "InstallationMismatchEvidence" e JOIN "InstallationBillingTask" b ON b."mismatchId"=e."mismatchId" AND b."kind"='MISMATCH_VISIT_FEE' WHERE e."fileId"=OLD."id") BEGIN SELECT RAISE(ABORT,'billed mismatch evidence file is immutable'); END;

CREATE TRIGGER "InstallationBillingTask_mismatch_approval_guard" BEFORE INSERT ON "InstallationBillingTask"
WHEN NEW."kind"='MISMATCH_VISIT_FEE' AND (NEW."mismatchId" IS NULL OR NOT EXISTS (SELECT 1 FROM "InstallationMismatch" m JOIN "InstallationOrder" o ON o."id"=m."orderId" JOIN "InstallationMismatchEvidence" e ON e."mismatchId"=m."id" AND e."orderId"=m."orderId" JOIN "InstallationFile" f ON f."id"=e."fileId" AND f."id"=m."evidenceFileId" WHERE m."id"=NEW."mismatchId" AND m."orderId"=NEW."orderId" AND m."coordinatorApprovedAt" IS NOT NULL AND m."evidenceStatus"='VERIFIED_PRIVATE_FILE' AND m."evidenceFileId" IS NOT NULL AND m."evidenceVerifiedAt" IS NOT NULL AND ((typeof(m."evidenceVerifiedAt") IN ('integer','real') AND m."evidenceVerifiedAt"<=CAST(strftime('%s','now') AS INTEGER)*1000) OR (typeof(m."evidenceVerifiedAt")='text' AND julianday(m."evidenceVerifiedAt")<=julianday('now'))) AND f."orderId"=NEW."orderId" AND f."purpose"='MISMATCH_EVIDENCE' AND f."status"='READY' AND f."softDeletedAt" IS NULL AND f."byteSize">0 AND length(f."sha256")=64 AND f."sha256" NOT GLOB '*[^0-9a-f]*' AND EXISTS (SELECT 1 FROM "InstallationFileAuditEvent" a WHERE a."fileId"=f."id" AND a."orderId"=NEW."orderId" AND a."action"='INSTALLATION_PRIVATE_FILE_READY') AND o."visitFeeStatus"='APPROVED' AND o."visitFeePolicyId" IS NOT NULL AND o."visitFeeGrossAmount" IS NOT NULL AND length(trim(COALESCE(o."visitFeeClauseText",'')))>0 AND o."visitFeeClauseVersion" IS NOT NULL AND o."visitFeeLegalApprovedAt" IS NOT NULL AND o."visitFeeClientAcceptedAt" IS NOT NULL AND NEW."grossAmount"=o."visitFeeGrossAmount"))
BEGIN SELECT RAISE(ABORT,'installation billing requires ready same-order private evidence and an accepted visit-fee snapshot'); END;
CREATE TRIGGER "InstallationBillingTask_mismatch_approval_update_guard" BEFORE UPDATE OF "orderId","mismatchId","kind","grossAmount" ON "InstallationBillingTask"
WHEN NEW."kind"='MISMATCH_VISIT_FEE' AND (NEW."mismatchId" IS NULL OR NOT EXISTS (SELECT 1 FROM "InstallationMismatch" m JOIN "InstallationOrder" o ON o."id"=m."orderId" JOIN "InstallationMismatchEvidence" e ON e."mismatchId"=m."id" AND e."orderId"=m."orderId" JOIN "InstallationFile" f ON f."id"=e."fileId" AND f."id"=m."evidenceFileId" WHERE m."id"=NEW."mismatchId" AND m."orderId"=NEW."orderId" AND m."coordinatorApprovedAt" IS NOT NULL AND m."evidenceStatus"='VERIFIED_PRIVATE_FILE' AND m."evidenceFileId" IS NOT NULL AND m."evidenceVerifiedAt" IS NOT NULL AND ((typeof(m."evidenceVerifiedAt") IN ('integer','real') AND m."evidenceVerifiedAt"<=CAST(strftime('%s','now') AS INTEGER)*1000) OR (typeof(m."evidenceVerifiedAt")='text' AND julianday(m."evidenceVerifiedAt")<=julianday('now'))) AND f."orderId"=NEW."orderId" AND f."purpose"='MISMATCH_EVIDENCE' AND f."status"='READY' AND f."softDeletedAt" IS NULL AND f."byteSize">0 AND length(f."sha256")=64 AND f."sha256" NOT GLOB '*[^0-9a-f]*' AND EXISTS (SELECT 1 FROM "InstallationFileAuditEvent" a WHERE a."fileId"=f."id" AND a."orderId"=NEW."orderId" AND a."action"='INSTALLATION_PRIVATE_FILE_READY') AND o."visitFeeStatus"='APPROVED' AND o."visitFeePolicyId" IS NOT NULL AND o."visitFeeGrossAmount" IS NOT NULL AND length(trim(COALESCE(o."visitFeeClauseText",'')))>0 AND o."visitFeeClauseVersion" IS NOT NULL AND o."visitFeeLegalApprovedAt" IS NOT NULL AND o."visitFeeClientAcceptedAt" IS NOT NULL AND NEW."grossAmount"=o."visitFeeGrossAmount"))
BEGIN SELECT RAISE(ABORT,'installation billing requires ready same-order private evidence and an accepted visit-fee snapshot'); END;
