import { expect, test } from '@playwright/test'
import bcrypt from 'bcryptjs'
import { PrismaClient } from '@/generated/prisma'
import { dispatchAcceptanceEmailLink } from '@/lib/installations/acceptance-client'

const databaseUrl = process.env.E2E_DATABASE_URL
if (!databaseUrl?.startsWith('file:/tmp/walldecor-installations-e2e-')) throw new Error('Acceptance E2E requires isolated SQLite')
const password = 'Acceptance-E2E-2026!'
let db: PrismaClient
let orderId: string

test.beforeAll(async () => {
  db = new PrismaClient({ datasources: { db: { url: databaseUrl } } })
  await db.$executeRawUnsafe('PRAGMA foreign_keys = ON')
  await db.costCenter.create({ data: { id: 'ACCEPT-E2E', name: 'Odbiory E2E' } })
  const [owner, backup, installer] = await Promise.all([
    db.employee.create({ data: { firstName: 'Anna', lastName: 'Odbiór', email: 'accept-owner@example.test', position: 'Opiekun', costCenterId: 'ACCEPT-E2E', startDate: new Date('2026-01-01'), active: true } }),
    db.employee.create({ data: { firstName: 'Bartek', lastName: 'Odbiór', email: 'accept-backup@example.test', position: 'Opiekun', costCenterId: 'ACCEPT-E2E', startDate: new Date('2026-01-01'), active: true } }),
    db.employee.create({ data: { firstName: 'Celina', lastName: 'Odbiór', email: 'accept-installer@example.test', position: 'Wykonawca', costCenterId: 'ACCEPT-E2E', startDate: new Date('2026-01-01'), active: true } }),
  ])
  await db.user.create({ data: { username: 'acceptinstaller', email: 'accept-installer@example.test', name: 'Celina Odbiór', role: 'INSTALLER', employeeId: installer.id, passwordHash: await bcrypt.hash(password, 10), passwordChangedAt: new Date() } })
  await db.user.create({ data: { username: 'acceptowner', email: owner.email, name: 'Anna Odbiór', role: 'EMPLOYEE', employeeId: owner.id, passwordHash: await bcrypt.hash(password, 10), passwordChangedAt: new Date() } })
  await db.user.create({ data: { username: 'acceptadmin', email: 'accept-admin@example.test', name: 'Administrator Odbioru', role: 'ADMIN', passwordHash: await bcrypt.hash(password, 10), passwordChangedAt: new Date() } })
  const order = await db.installationOrder.create({ data: {
    number: 'MON-ACCEPT-E2E', client: { create: { name: 'Ewa Klientka', email: 'ewa@example.test', phone: '+48 500 100 200' } },
    addressStreet: 'Warsztatowa', addressBuildingNumber: '4', addressPostalCode: '00-001', addressCity: 'Warszawa',
    primaryEmployee: { connect: { id: owner.id } }, backupEmployee: { connect: { id: backup.id } },
  } })
  orderId = order.id
  const category = await db.installationCatalogCategory.create({ data: { name: 'Tapetowanie', nameKey: 'tapetowanie-odbior-e2e' } })
  const room = await db.installationRoom.create({ data: { orderId, name: 'Salon' } })
  const scope = await db.installationScope.create({ data: { roomId: room.id, catalogCategoryId: category.id, name: 'Tapetowanie ściany' } })
  await db.installationScopeAssignment.create({ data: { orderId, scopeId: scope.id, employeeId: installer.id, createdById: 'e2e' } })
  await db.installationVisit.create({ data: {
    orderId, status: 'CONFIRMED', startsAt: new Date(Date.now() - 2 * 60 * 60 * 1000), endsAt: new Date(Date.now() - 60 * 60 * 1000), createdById: 'e2e',
    scopes: { create: { orderId, scopeId: scope.id } },
  } })
})

test.afterAll(async () => { await db?.$disconnect() })

test('installer, client and coordinator complete remarks, revision, PDF and invoice task', async ({ page, browser }, info) => {
  test.setTimeout(90_000)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/login')
  await page.locator('input[name="username"]').fill('acceptinstaller')
  await page.locator('input[type="password"]').fill(password)
  await page.getByRole('button', { name: /Zaloguj/ }).click()
  await expect(page).toHaveURL(/\/(dashboard|finance|installations)/)
  await page.goto(`/installations/${orderId}`)
  await expect(page.locator('#acceptance').getByRole('heading', { name: 'Protokoły odbioru' })).toBeVisible()
  await page.locator('#acceptance').getByRole('button', { name: 'Przygotuj protokół' }).click()
  await expect(page).toHaveURL(/\/protocols\//)
  await expect(page.getByRole('heading', { name: 'Tapetowanie', exact: true })).toBeVisible()
  await expect(page.getByText('Tapetowanie ściany')).toBeVisible()
  await page.getByLabel('Wynik pracy').selectOption('PARTIAL')
  await page.getByRole('button', { name: 'Podpisz protokół' }).click()
  await expect(page.getByText('Złóż podpis przed zapisaniem.')).toBeVisible()
  await page.getByLabel('Opis powodu (wymagany)').fill('Pozostał fragment przy drzwiach.')
  await page.getByLabel('Pole podpisu wykonawcy').scrollIntoViewIfNeeded()
  const box = await page.getByLabel('Pole podpisu wykonawcy').boundingBox()
  if (!box) throw new Error('Signature canvas missing')
  await page.mouse.move(box.x + 30, box.y + 70)
  await page.mouse.down()
  await page.mouse.move(box.x + 130, box.y + 45, { steps: 8 })
  await page.mouse.move(box.x + 230, box.y + 75, { steps: 8 })
  await page.mouse.up()
  await page.getByRole('button', { name: 'Podpisz protokół' }).click()
  await expect(page.getByText('Podpis wykonawcy został zapisany.')).toBeVisible()
  await page.screenshot({ path: info.outputPath('signed-protocol-mobile.png'), fullPage: true })
  const stored = await db.installationAcceptanceProtocol.findFirstOrThrow({ where: { orderId } })
  expect(stored.status).toBe('INSTALLER_SIGNED')
  expect(stored.contentHash).toMatch(/^[a-f0-9]{64}$/)
  expect(await db.installationFile.count({ where: { acceptanceProtocolId: stored.id } })).toBe(0)
  await page.getByRole('button', { name: 'Otwórz widok klienta na tym telefonie' }).click()
  await expect(page).toHaveURL(/\/p\/[A-Za-z0-9_-]+/)
  await expect(page.getByRole('heading', { name: 'Sprawdź wykonane prace' })).toBeVisible()
  await expect(page.getByText('Pozostał fragment przy drzwiach.')).toBeVisible()
  await expect(page.getByRole('link', { name: /Wróć do karty/ })).toHaveCount(0)
  await expect(page.getByText('accept-owner@example.test')).toHaveCount(0)
  await page.getByLabel('Odbieram z uwagami').check()
  await page.getByLabel('Imię').fill('Ewa')
  await page.getByLabel('Nazwisko').fill('Klientka')
  await page.getByLabel('Kim jesteś wobec zlecenia?').fill('klientka')
  await page.getByLabel('Uwagi').fill('Proszę dokończyć przy drzwiach.')
  await page.getByLabel('Pole podpisu klienta').scrollIntoViewIfNeeded()
  const clientBox = await page.getByLabel('Pole podpisu klienta').boundingBox()
  if (!clientBox) throw new Error('Client signature canvas missing')
  await page.mouse.move(clientBox.x + 20, clientBox.y + 75)
  await page.mouse.down()
  await page.mouse.move(clientBox.x + 130, clientBox.y + 50, { steps: 8 })
  await page.mouse.move(clientBox.x + 240, clientBox.y + 75, { steps: 8 })
  await page.mouse.up()
  await page.getByRole('button', { name: 'Potwierdź decyzję' }).click()
  await expect(page.getByRole('heading', { name: 'Odebrano z uwagami' })).toBeVisible()
  await page.screenshot({ path: info.outputPath('client-response-mobile.png'), fullPage: true })
  const accepted = await db.installationAcceptanceProtocol.findUniqueOrThrow({ where: { id: stored.id } })
  expect(accepted.status).toBe('ACCEPTED_WITH_REMARKS')
  expect(accepted.clientSignature).not.toBeNull()
  const expectedRecipients = await db.user.count({ where: { isActive: true, OR: [{ role: 'ADMIN' }, { username: 'acceptowner' }] } })
  expect(await db.notification.count({ where: { type: 'installation_acceptance_exception', link: `/installations/${orderId}#acceptance` } })).toBe(expectedRecipients)
  expect(await db.installationAcceptanceInvoiceTask.count({ where: { orderId } })).toBe(0)
  const clientPdf = await page.request.get(`${page.url().replace(/\/p\/.+$/, '')}/api/public/acceptance/${page.url().split('/').pop()}/pdf`)
  expect(clientPdf.ok()).toBeTruthy()
  expect(Buffer.from(await clientPdf.body()).subarray(0, 4).toString()).toBe('%PDF')
  const installerPdf = await page.request.get(`/api/installations/${orderId}/protocols/${stored.id}/pdf`)
  expect(installerPdf.ok()).toBeTruthy()
  expect(Buffer.from(await installerPdf.body()).equals(Buffer.from(await clientPdf.body()))).toBe(true)

  const adminContext = await browser.newContext({ viewport: { width: 1200, height: 900 } })
  const adminPage = await adminContext.newPage()
  await adminPage.goto('/login')
  await adminPage.locator('input[name="username"]').fill('acceptadmin')
  await adminPage.locator('input[type="password"]').fill(password)
  await adminPage.getByRole('button', { name: /Zaloguj/ }).click()
  await expect(adminPage).toHaveURL(/\/(dashboard|finance|installations)/)
  await adminPage.goto(`/installations/${orderId}#acceptance`)
  await expect(adminPage.getByRole('heading', { name: 'Protokoły odbioru' })).toBeVisible()
  await expect(adminPage.getByText('Etap otwarty: po poprawkach wymagany nowy podpis wykonawcy i klienta.')).toBeVisible()
  await adminPage.getByRole('button', { name: 'Nowa wersja' }).click()
  await expect.poll(async () => db.installationAcceptanceProtocol.count({ where: { orderId } })).toBe(2)
  const revision = await db.installationAcceptanceProtocol.findFirstOrThrow({ where: { orderId, revision: 2 } })
  expect(revision.status).toBe('DRAFT')

  await page.goto(`/installations/${orderId}`)
  await page.locator('#acceptance').getByRole('button', { name: 'Otwórz protokół' }).click()
  await expect(page.getByText('wersja 2')).toBeVisible()
  await page.getByLabel('Wynik pracy').selectOption('DONE')
  await page.getByLabel('Pole podpisu wykonawcy').scrollIntoViewIfNeeded()
  const secondSignature = await page.getByLabel('Pole podpisu wykonawcy').boundingBox()
  if (!secondSignature) throw new Error('Revised signature canvas missing')
  await page.mouse.move(secondSignature.x + 30, secondSignature.y + 70)
  await page.mouse.down()
  await page.mouse.move(secondSignature.x + 130, secondSignature.y + 45, { steps: 8 })
  await page.mouse.move(secondSignature.x + 230, secondSignature.y + 75, { steps: 8 })
  await page.mouse.up()
  await page.getByRole('button', { name: 'Podpisz protokół' }).click()
  await expect(page.getByText('Podpis wykonawcy został zapisany.')).toBeVisible()
  await page.getByRole('button', { name: 'Otwórz widok klienta na tym telefonie' }).click()
  await expect(page).toHaveURL(/\/p\/[A-Za-z0-9_-]+/)
  await page.getByLabel('Imię').fill('Ewa')
  await page.getByLabel('Nazwisko').fill('Klientka')
  await page.getByLabel('Kim jesteś wobec zlecenia?').fill('klientka')
  await page.getByLabel('Pole podpisu klienta').scrollIntoViewIfNeeded()
  const finalSignature = await page.getByLabel('Pole podpisu klienta').boundingBox()
  if (!finalSignature) throw new Error('Final client signature canvas missing')
  await page.mouse.move(finalSignature.x + 20, finalSignature.y + 75)
  await page.mouse.down()
  await page.mouse.move(finalSignature.x + 130, finalSignature.y + 50, { steps: 8 })
  await page.mouse.move(finalSignature.x + 240, finalSignature.y + 75, { steps: 8 })
  await page.mouse.up()
  await page.getByRole('button', { name: 'Potwierdź decyzję' }).click()
  await expect(page.getByRole('heading', { name: 'Odebrano' })).toBeVisible()
  expect((await db.installationAcceptanceProtocol.findUniqueOrThrow({ where: { id: revision.id } })).status).toBe('ACCEPTED')
  const task = await db.installationAcceptanceInvoiceTask.findFirstOrThrow({ where: { orderId } })
  expect(task.title).toBe('Wystawić fakturę')
  expect(task.status).toBe('PENDING')
  expect(task.acceptedProtocolId).toBe(revision.id)
  await adminPage.reload()
  await expect(adminPage.getByText('Zadanie: Wystawić fakturę · do wykonania')).toBeVisible()

  // A second work type uses a separate link and a client browser without a session.
  const installer = await db.employee.findFirstOrThrow({ where: { email: 'accept-installer@example.test' } })
  const painting = await db.installationCatalogCategory.create({ data: { name: 'Malowanie', nameKey: 'malowanie-odbior-e2e' } })
  const paintingRoom = await db.installationRoom.create({ data: { orderId, name: 'Sypialnia' } })
  const paintingScope = await db.installationScope.create({ data: { roomId: paintingRoom.id, catalogCategoryId: painting.id, name: 'Malowanie ściany' } })
  await db.installationScopeAssignment.create({ data: { orderId, scopeId: paintingScope.id, employeeId: installer.id, createdById: 'e2e' } })
  await db.installationVisit.create({ data: {
    orderId, status: 'CONFIRMED', startsAt: new Date(Date.now() - 60 * 60 * 1000), endsAt: new Date(Date.now() - 30 * 60 * 1000), createdById: 'e2e',
    scopes: { create: { orderId, scopeId: paintingScope.id } },
  } })
  await page.goto(`/installations/${orderId}`)
  await page.locator('#acceptance').getByRole('button', { name: 'Przygotuj protokół' }).click()
  await expect(page.getByRole('heading', { name: 'Malowanie', exact: true })).toBeVisible()
  await page.getByLabel('Wynik pracy').selectOption('DONE')
  await page.getByLabel('Pole podpisu wykonawcy').scrollIntoViewIfNeeded()
  const emailSignature = await page.getByLabel('Pole podpisu wykonawcy').boundingBox()
  if (!emailSignature) throw new Error('Email protocol signature canvas missing')
  await page.mouse.move(emailSignature.x + 30, emailSignature.y + 70)
  await page.mouse.down()
  await page.mouse.move(emailSignature.x + 130, emailSignature.y + 45, { steps: 8 })
  await page.mouse.move(emailSignature.x + 230, emailSignature.y + 75, { steps: 8 })
  await page.mouse.up()
  await page.getByRole('button', { name: 'Podpisz protokół' }).click()
  await expect(page.getByText('Podpis wykonawcy został zapisany.')).toBeVisible()
  const paintingProtocol = await db.installationAcceptanceProtocol.findFirstOrThrow({ where: { orderId, groupKey: `category:${painting.id}` } })
  const sent: string[] = []
  await dispatchAcceptanceEmailLink(db, paintingProtocol.id, installer.id, 'http://localhost:3000', async (message) => { sent.push(message.text) })
  const emailUrl = sent[0]?.match(/https?:\/\/[^\s]+\/p\/[A-Za-z0-9_-]{43}/)?.[0]
  expect(emailUrl).toBeTruthy()
  const clientContext = await browser.newContext({ viewport: { width: 390, height: 844 } })
  const clientPage = await clientContext.newPage()
  await clientPage.goto(emailUrl!)
  await expect(clientPage.getByRole('heading', { name: 'Sprawdź wykonane prace' })).toBeVisible()
  await expect(clientPage.getByText('Malowanie ściany')).toBeVisible()
  await clientPage.getByLabel('Odbieram', { exact: true }).check()
  await clientPage.getByLabel('Imię').fill('Ewa')
  await clientPage.getByLabel('Nazwisko').fill('Klientka')
  await clientPage.getByLabel('Kim jesteś wobec zlecenia?').fill('klientka')
  await clientPage.getByLabel('Pole podpisu klienta').scrollIntoViewIfNeeded()
  const emailClientSignature = await clientPage.getByLabel('Pole podpisu klienta').boundingBox()
  if (!emailClientSignature) throw new Error('Email client signature canvas missing')
  await clientPage.mouse.move(emailClientSignature.x + 20, emailClientSignature.y + 75)
  await clientPage.mouse.down()
  await clientPage.mouse.move(emailClientSignature.x + 130, emailClientSignature.y + 50, { steps: 8 })
  await clientPage.mouse.move(emailClientSignature.x + 240, emailClientSignature.y + 75, { steps: 8 })
  await clientPage.mouse.up()
  await clientPage.getByRole('button', { name: 'Potwierdź decyzję' }).click()
  await expect(clientPage.getByRole('heading', { name: 'Odebrano' })).toBeVisible()
  expect((await db.installationAcceptanceProtocol.findUniqueOrThrow({ where: { id: paintingProtocol.id } })).status).toBe('ACCEPTED')
  expect(await db.installationAcceptanceInvoiceTask.count({ where: { orderId, groupKey: `category:${painting.id}` } })).toBe(1)
  const emailedPdf = await clientPage.request.get(`/api/public/acceptance/${emailUrl!.split('/').pop()}/pdf`)
  expect(emailedPdf.ok()).toBeTruthy()
  expect(Buffer.from(await emailedPdf.body()).subarray(0, 4).toString()).toBe('%PDF')
  const privatePdf = await clientPage.request.get(`/api/installations/${orderId}/protocols/${paintingProtocol.id}/pdf`)
  expect(privatePdf.url()).toContain('/login?')
  expect(privatePdf.headers()['content-type']).not.toContain('application/pdf')
  await db.installationAcceptanceLink.updateMany({ where: { protocolId: paintingProtocol.id, channel: 'EMAIL' }, data: { expiresAt: new Date('2020-01-01') } })
  const expiredPdf = await clientPage.request.get(`/api/public/acceptance/${emailUrl!.split('/').pop()}/pdf`)
  expect(expiredPdf.status()).toBe(404)
  await clientContext.close()
  await db.installationOrder.update({ where: { id: orderId }, data: { status: 'ARCHIVED', archivedAt: new Date() } })
  await adminPage.reload()
  await expect(adminPage.getByRole('heading', { name: 'Protokoły odbioru' })).toBeVisible()
  await expect(adminPage.getByText('Zadanie: Wystawić fakturę · do wykonania').first()).toBeVisible()
  await expect(adminPage.getByRole('button', { name: 'Nowa wersja' })).toHaveCount(0)
  const archivedPdf = await adminPage.request.get(`/api/installations/${orderId}/protocols/${paintingProtocol.id}/pdf`)
  expect(archivedPdf.ok()).toBeTruthy()
  await page.goto(`/installations/${orderId}`)
  const paintingRow = page.locator('#acceptance').getByRole('heading', { name: 'Malowanie', exact: true }).locator('..').locator('..')
  await expect(paintingRow.getByRole('button', { name: 'Otwórz protokół' })).toBeVisible()
  await paintingRow.getByRole('button', { name: 'Otwórz protokół' }).click()
  await expect(page.getByRole('link', { name: 'Pobierz PDF protokołu' })).toBeVisible()
  await adminContext.close()
})
